### ISSUE TITLE
I get some error

### ISSUE THREAD

**Issue by ghost** [renpytom/rapt-pygame-example#1]
I did exactly what stands in the readme, but when I try it I get this error:

```
Traceback (most recent call last):
  File "android.py", line 69, in <module>
    main()
  File "android.py", line 54, in main
    build.build(iface, args.argument[0], args.argument[1:], launch=args.launch)
  File "buildlib/rapt/build.py", line 474, in build
    config = config)
  File "buildlib/rapt/build.py", line 116, in render
    f = file(dest, "wb")
IOError: [Errno 2] No such file or directory: '/media/wb9688/sdcard/rapt/res/values/strings.xml'
```

**Comment by ghost** [comment]
I found the problem.

**Comment by renpytom** [comment]
What was the problem?

**Comment by ghost** [comment]
I cloned the repo, but I had to download it from that nightly site, because some files aren't included. Why can't I just clone the repo from https://github.com/renpy/rapt.git?

**Comment by renpytom** [comment]
It's because rapt.git (and my fork of python-for-android, which it uses) require the NDK, and quite a bit of work to build. The binary distro already has done that for you.

**Comment by ghost** [comment]
Are there instructions for manually building RAPT?

**Comment by renpytom** [comment]
Not yet. It's kind of a pain in the ass to document, since you need pygame_sdl2 and Ren'Py to do the build, as well as a number of android tools.

**Comment by ghost** [comment]
Can't you make a bash or python script to set up the Android tools, pygame_sdl2, Ren'Py and the other stuff? Are you using a buildbot for building the nightlies?
