### ISSUE TITLE
Amazon package not available

### ISSUE THREAD

**Issue by DeepakLabh** [renpytom/rapt-pygame-example#8]
Hi, after following the instructions the last build command gave following error:
[javac] home/d/rapt/src/org/renpy/iap/AmazonStore.java:6: error: package com.amazon.device.iap does not exist
...

I tried downloading the package from https://developer.amazon.com/sdk-download , but it didn't have any class files inside.

**Comment by DeepakLabh** [comment]
Extracted the jar file and it's working

**Comment by LerikP** [comment]
Hi, @DeepakLabh .
Would you mind сlarifying, where have you put extracted files from jar?
